databases:
  - name: rail_db
    databaseName: rail_db
    user: rail_user
    plan: free

services:
  - type: web
    name: rail-banking-app
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate --no-input"
    startCommand: "gunicorn RAILmicrofinace.wsgi:application --bind 0.0.0.0:$PORT --log-level debug"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: DATABASE_URL
        fromDatabase:
          name: rail_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: railswissbank.onrender.com
      - key: DJANGO_SETTINGS_MODULE
        value: RAILmicrofinace.settings
