databases:
  - name: rail_db
    databaseName: rail_db
    user: rail_user
    plan: free

services:
  - type: web
    name: rail-banking-app
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn RAILmicrofinace.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: DATABASE_URL
        fromDatabase:
          name: rail_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        sync: false
